Спринт № 9. Ревью 1. Controllers films users
FedoRScorpioN/java-filmorate pull request #1
Opened 2022-11-02 18:47 UTC by FedoRScorpioN

2022-11-03 07:21 UTC, LexLippi requested changes
Привет!

Неплохая работа, но есть замечания, которые необходимо обязательно исправить!

Желаю удачи!!!

2022-11-03 07:21 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private void checkUsers(@RequestBody Film filmToAdd) {
Почему это называется `checkUsers`, если это никакого отеошения к пользователям не имеет?

2022-11-03 07:21 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private boolean alreadyExistsUsers(Film filmToAdd, Film film) {
Аналогично, что-то не так с названием.

1. Убрать `users`
2. Не хватает глагола - `isFilmAlreadyExists`

2022-11-03 07:21 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            log.warn("Фильм к добавлению: {}", filmToAdd);
1. Наверное, "Фильм к добавлению уже существует", иначе не очень понятно, что это сообщение должно значить

2. Если уж начал использовать Stream API, то можно полностью сделать этот метод с его использованием:

`anyMatch` -> `filter`

После этого добавить
```
.map(film -> {
    log.warn(...);
    throw new ValidationException("");
});
```

2022-11-03 07:21 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private void validationUsers(@Valid @RequestBody Film film) {
Почему `users`?

2022-11-03 07:21 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        checkUsers(film);
А почему здесь эта проверка. Кажется при обновлении вполне нормально, что фильм существует

2022-11-03 07:21 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        checkUsers(user);
При обновлении пользователя, вполне допустимо, чтобы похожий пользователь уже существовал

2022-11-03 07:21 UTC, LexLippi commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +class FilmorateApplicationTests {
Этого класса может и не быть, 
а вот тесты проверяющие валидацию должны быть обязательно!

2022-11-04 05:56 UTC, FedoRScorpioN commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private void checkUsers(@RequestBody Film filmToAdd) {
Исправил.

2022-11-04 05:56 UTC, FedoRScorpioN commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private boolean alreadyExistsUsers(Film filmToAdd, Film film) {
Исправил.

2022-11-04 05:57 UTC, FedoRScorpioN commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private void validationUsers(@Valid @RequestBody Film film) {
Перепутал названия. Исправил.

2022-11-04 05:59 UTC, FedoRScorpioN commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        checkUsers(film);
Не стал исправлять.
Да, при обновление конечно нормально, что данный фильм существует. Но, у меня в условии if стоит "!", то есть исключение выбрасывается если фильм отсутствует в коллекции. Я думаю, что обновить несуществующий объект невозможно.

2022-11-04 06:03 UTC, FedoRScorpioN commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        checkUsers(user);
Исправил.

2022-11-04 11:50 UTC, FedoRScorpioN commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            log.warn("Фильм к добавлению: {}", filmToAdd);
Оставил как есть. после anyMatch ничего не включается.

2022-11-05 17:01 UTC, FedoRScorpioN commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +class FilmorateApplicationTests {
Добавил тесты для валидации.

2022-11-07 08:15 UTC, LexLippi approved these changes
Привет!

Хорошая работа!

Желаю удачи в следующих спринтах!!!

2022-11-14 19:06 UTC, merged