Спринт № 10. Ревью № 1.
FedoRScorpioN/java-filmorate pull request #2
Opened 2022-11-17 18:12 UTC by FedoRScorpioN

2022-11-19 13:57 UTC, LexLippi requested changes
Привет!

Хорошая работа!
Есть несколько небольших замечаний, которые необходимо поправить!

Желаю удачи!

2022-11-19 13:57 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserStorage.java
> +    Map<Integer, User> getUsers();
Тебе не кажется, что эти два метода делают в сущности одно и то же. Одного из них было бы вполне достаточно. Как по мне того, который `findAllUsers`

2022-11-19 13:57 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +        }
Лучше сначала проводить всю валидацию, а потом устанавливать имя. Потому что читающему может быть непонятно в чем логика такого поведения

2022-11-19 13:57 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +    }
Кажется, этот метод не нужен. Весь его функционал можно получить с помощью других методов

2022-11-19 13:57 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        if (!userStorage.getUsers().containsKey(firstId) || !userStorage.getUsers().containsKey(secondId)) {
Можно не проверять наличие пользователя с помощью `containsKey`, а просто анализировать, что вернет метод получения пользователя по идентификатору. Если пользователя нет, он вернет `null`

2022-11-19 13:57 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +public class FilmService {
Замечания, аналоигчные `UserService`

2022-11-19 15:32 UTC, FedoRScorpioN commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserStorage.java
> +    Map<Integer, User> getUsers();
Думаю нет. Потому что у них немного разные функции:
Collection<User> findAllUsers(); //возвращает список всех пользователей.
Map<Integer, User> getUsers(); //возвращает определённого пользователя по id. 

Если настаиваете, буду думать как их объединить в один метод...

2022-11-19 16:01 UTC, FedoRScorpioN commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +        }
Логично. Сначала надо проверить, что всё остальное соответствует условиям, а потом уже регистрировать пользователя. 
Исправил.

2022-11-19 16:02 UTC, FedoRScorpioN commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +    }
Думаю нет. Потому что у них немного разные функции:
Collection findAllFilms(); //возвращает список всех пользователей.
Map<Integer, Film> getFilms(); //возвращает определённого пользователя по id.

Если настаиваете, буду думать как их объединить в один метод...

2022-11-19 16:06 UTC, FedoRScorpioN commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        if (!userStorage.getUsers().containsKey(firstId) || !userStorage.getUsers().containsKey(secondId)) {
Исправил.

2022-11-19 16:42 UTC, FedoRScorpioN commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +public class FilmService {
Исправил.

2022-11-21 07:19 UTC, LexLippi approved these changes
Привет!

Хорошая работа. 
Принимаю её, можешь глянуть тот комментарий, который я написал, чтобы в будущем было понять, как если что избавиться от третьего метода получения. Но на данный момент давай оставим все как есть!

Желаю удачи в следующих спринтах!

2022-11-21 07:19 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +    }
Ок, давай оставим, как есть. Просто я имел в виду, что двумя методами `getUser(int id)`, `findAll()` можно обойтись. Один возвращает пользователя по идентификатору, второй возвращает список всех пользователей (для фильмов аналогично).

Соответственно, с помощью `getUser(int id)` можно проверять существует ли пользователь. 
2 варианта:

1. Проверять не равен ли пользователь, который вернул данный метод `null`
2. Инкапсулировать логику проверки внутрь этого метода, и если `users.containsKey(id)` - false, то выбрасывать исключение, что пользователь не найден, и где необходимо его обрабатывать

2022-12-18 18:48 UTC, merged