Спринт № 11. Ревью № 1.
FedoRScorpioN/java-filmorate pull request #3
Opened 2022-12-20 20:03 UTC by FedoRScorpioN

2022-12-21 08:18 UTC, LexLippi requested changes
Привет!

Неплохая работа!
Общие замеания: предыдущие реализации хранилищ не надо удалять, предыдущие тесты не надо удалять.
Есть некоторые замечания. которые я оставил только в одном классе, но если ты видишь в другом такую же ситуацию, то там тоже надо исправить. Я решил не играть в попугая, и не повторять 25 раз одно и то же.

Желаю удачи!

2022-12-21 08:18 UTC, LexLippi commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS FILMS
Схема, описанная в этом файле не совпадает с тем, что представлено в ER-диаграмме.
Надо обновить картинку

2022-12-21 08:18 UTC, LexLippi commented on src/main/resources/schema.sql
> +ALTER TABLE FILM_GENRE
Аналогичное ограничение необходимо добавить в таблицы `FRIENDSHIP` и `LIKES`

2022-12-21 08:18 UTC, LexLippi commented on src/main/resources/schema.sql
> +    CONSTRAINT uc_User_Email UNIQUE (EMAIL)
А логин не должен быть уникальным?

2022-12-21 08:18 UTC, LexLippi commented on src/main/resources/data.sql
> +    ALTER COLUMN LIKE_ID RESTART WITH 1;
Точно хотим так делать. В таком случае при каждом обновлении приложения и запуске всех миграций мы будем удалять все то, что мы накопили в БД с последнего релиза.

Это странный способ работы

2022-12-21 08:18 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/UserDbStorage.java
> +        return getByIdUser(id);
Лучше не использовать лишние запросы. Это может замедлить работу нашего метода, что не очень хорошо с точки зрения практической работы с  API

2022-12-21 08:18 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/UserDbStorage.java
> +        return getByIdUser(user.getId());
Аналогично тому, что выше написал

2022-12-21 08:18 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/UserDbStorage.java
> +        User user;
не очень ясно зачем здесь заводить эту локальную переменную, мы можем сделать `return` внутри блока `try`, и возвращать `null`, во всех остальных случаях. Это будет более наглядно, и не будем тратить строки на бессмысленное объявление переменной

2022-12-21 08:18 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/UserDbStorage.java
> +    }
Зачем нам два одинаковых метода?

2022-12-21 08:18 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/UserDbStorage.java
> +        boolean friendAccepted;
зачем объявлть эту переменную отдельно от инициализации?

2022-12-21 08:18 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/UserDbStorage.java
> +        return false;
Почему `false`?

2022-12-21 08:18 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/UserDbStorage.java
> +    }
Стоит произвести рефакторинг и избавиться от этого метода в интерфейсе, если мы его не реализовываем.
А делать это таким образом - плохой паттерн, потому что чаще всего никто не смотрит на реализацию интерфейса. Другие программисты будут полагаться на то, что этот метод будет работать корректно, а это не так.

2022-12-21 08:18 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/UserDbStorage.java
> +    }
Выше уже есть тот же самый метод. Зачем реализовывать его ещё раз?

2022-12-21 08:18 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/GenreDbStorage.java
> +        String sqlQuery = "SELECT GENRE_ID, GENRE_NAME FROM GENRES ORDER BY GENRE_ID";
почему где-то *, а где-то явное перечисление полей?

2022-12-21 08:18 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/GenreDbStorage.java
> +        return true;
Почему `true`?

2022-12-21 08:18 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/GenreDbStorage.java
> +        return true;
Почему `true`?

2022-12-21 08:18 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Film getByIdFilms(@PathVariable String id) {
Почему на `String` изменил?

2022-12-21 09:27 UTC, FedoRScorpioN commented on src/main/resources/schema.sql
> +ALTER TABLE FILM_GENRE
Исправил.

2022-12-21 09:29 UTC, FedoRScorpioN commented on src/main/resources/schema.sql
> +    CONSTRAINT uc_User_Email UNIQUE (EMAIL)
Согласен. Упустил.

Исправил.

2022-12-21 10:26 UTC, FedoRScorpioN commented on src/main/resources/data.sql
> +    ALTER COLUMN LIKE_ID RESTART WITH 1;
Исправил.

2022-12-21 10:35 UTC, FedoRScorpioN commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/UserDbStorage.java
> +        return getByIdUser(id);
Исправил.

2022-12-21 11:44 UTC, FedoRScorpioN commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/UserDbStorage.java
> +    }
В первом случае он ...Map<Integer, User>...
Во втором просто ...User... но уже с объявленной сигнатурой.
Они используются в разных местах и работают немного по разному. 
Или надо его убрать отсюда и добавить в то место где они используется?

2022-12-21 11:49 UTC, FedoRScorpioN commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/GenreDbStorage.java
> +        String sqlQuery = "SELECT GENRE_ID, GENRE_NAME FROM GENRES ORDER BY GENRE_ID";
Согласен, вместо перечисления лучше указать *. Не везде сразу сделал.

Исправил.

2022-12-21 11:54 UTC, FedoRScorpioN commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/GenreDbStorage.java
> +        return true;
Происходит добавление "жанра" у фильма.  При добавлении метод сообщает, что жанр добавлен.

2022-12-21 11:55 UTC, FedoRScorpioN commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/GenreDbStorage.java
> +        return true;
А здесь в обратном направлении. Происходи удаление "жанра" у фильма и метод сообщает, что он удален.

2022-12-21 11:57 UTC, FedoRScorpioN commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Film getByIdFilms(@PathVariable String id) {
В методе "getFilmStored" используется соответствующая сигнатура.

2022-12-22 09:05 UTC, LexLippi requested changes
Привет!

Всё хорошо, осталась ещё пара небольших замечаний!

Желаю удачи!!!

2022-12-22 09:05 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +            return Integer.MIN_VALUE;
Мне кажется здесь правильнее `null` возвращать. Оно как раз для таких ситуаций и зарезервированно. Завтра для каких-то случае понадобится использовать отрицательные идентификаторы, и придется переписывать эту проверку.

Поэтому никогда не рекомендую кодировать некоторую бизнес-логику каким-то значение из диапазона. Для этого есть `null` или `Optional`

2022-12-22 09:05 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    private Integer parseId(final String id) {
Я бы не тащил эту проверку в сервис, а оставил её в контроллере. Что предполагает, что внутри сервиса мы уже работаем с корректными данными и типами данных, но это не принципиально

2022-12-22 09:05 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FilmDbStorage.java
> +        return true;
Я имел в виду, что в других местах ты делаешь:

```java
return jdbcTemplate.update(sqlQuery, film.getId()) != 0;
```

А здесь просто сразу `true` возвращаешь. Почему так?

2022-12-22 09:05 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/UserDbStorage.java
> +        return getByIdUser(id);
Вроде бы нет, ну или изменения не подтянулись в MR

2022-12-23 04:45 UTC, FedoRScorpioN commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS FILMS
Обновил в прошлый раз.

2022-12-23 06:59 UTC, LexLippi approved these changes
Привет!

Хорошая работа!

Желаю удачи в следующих спринтах!!!

2022-12-23 08:46 UTC, merged